# Generated by Django 6.0.7 on 2026-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_otpverification_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchsetting',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='contact_address',
            field=models.TextField(default='Carmel Bible Church ,Rajam'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='contact_email',
            field=models.EmailField(default='pastor@carmelbiblechurch.org', max_length=254),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='contact_phone',
            field=models.CharField(default='+87908 73190', max_length=20),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/syam.chevuri.9'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='hero_subtitle',
            field=models.CharField(default='నేను మరియు నా ఇంటివారు యెహోవాను సేవించెదము. – యెహోషువ 24:15.   ', max_length=500),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='https://www.google.com/maps/place/Carmel+Bible+Church,+A+Center+for+Bible+Knowledge+and+Spiritual+Edification/@18.4619347,83.6622747,71m/data=!3m1!1e3!4m6!3m5!1s0x3a3c76d85527eaa5:0x793d3e9a54020aea!8m2!3d18.4620398!4d83.6622632!16s%2Fg%2F11f03szfzb?entry=ttu&g_ep=EgoyMDI2MDcxNS4wIKXMDSoASAFQAw%3D%3D'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='mission',
            field=models.TextField(default='దేవుని వాక్యాన్ని ప్రకటించి, శిష్యులను తయారు చేసి, ప్రేమతో సమాజానికి సేవ చేయుట.'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='pastor_bio',
            field=models.TextField(default='Pastor Shyam Chevuri has been serving the community for over 13 years...'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='pastor_designation',
            field=models.CharField(default='Pastor - Bible Teacher', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='pastor_name',
            field=models.CharField(default='Pastor Shyam Chevuri', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='vision',
            field=models.TextField(default='క్రీస్తును తెలిసికొని, ఆయన ప్రేమను మరియు రక్షణను ప్రతి మనిషికి తెలియజేయుట.'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/@Shyam_Chevuri'),
        ),
    ]
