# Generated by Django 6.0.7 on 2026-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_remove_churchsetting_twitter_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com'),
        ),
    ]
