# Generated by Django 6.0.7 on 2026-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_alter_churchsetting_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetting',
            name='mission_telugu',
            field=models.TextField(default='దేవుని వాక్యాన్ని విశ్వసనీయంగా బోధించుట, సువార్తను ప్రకటించుట, శిష్యులను చేయుట, ప్రార్థనలో ఎదుగుట, ప్రేమతో సంఘానికీ సమాజానికీ సేవ చేయుట.'),
        ),
        migrations.AddField(
            model_name='churchsetting',
            name='vision_telugu',
            field=models.TextField(default='క్రీస్తును తెలిసికొని, ఆయనను అందరికీ తెలియజేస్తూ, దేవుని వాక్యములో స్థిరపడిన విశ్వాసుల సమాజాన్ని నిర్మించుట.'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='mission',
            field=models.TextField(default='To preach the Gospel, make disciples of all nations, and serve our local community with the love of Christ.'),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='vision',
            field=models.TextField(default='To know Christ and to make Him known through sound biblical teaching, discipleship, and evangelism.'),
        ),
    ]
