# Generated by Django 6.0.7 on 2026-07-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_churchsetting_mission_telugu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetting',
            name='hero_subtitle_telugu',
            field=models.CharField(default='దేవుని వాక్యము మా పాదములకు దీపమును, మా త్రోవకు వెలుగునై యున్నది.', max_length=500),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='hero_subtitle',
            field=models.CharField(default='A Bible-believing, Christ-centered, community-focused church.', max_length=500),
        ),
    ]
