# Generated by Django 6.0.7 on 2026-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_churchsetting_hero_subtitle_telugu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='churchsetting',
            name='hero_subtitle',
            field=models.CharField(default='', max_length=500),
        ),
    ]
