# Generated by Django 6.0.7 on 2026-07-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('admin', 'Only Admin')], default='all', max_length=10),
        ),
    ]
