# Generated by Django 6.0.7 on 2026-07-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_prayerrequest_visibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
