# Generated by Django 6.0.7 on 2026-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_alter_churchsetting_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsetting',
            name='map_embed_url',
            field=models.TextField(blank=True, default='https://www.google.com/maps?q=Carmel+Bible+Church,+Dolapeta,+Rajam,+Andhra+Pradesh+532127&output=embed', help_text='https://www.google.com/maps/place/Carmel+Bible+Church,+A+Center+for+Bible+Knowledge+and+Spiritual+Edification/@18.4619347,83.6622747,71m/data=!3m1!1e3!4m6!3m5!1s0x3a3c76d85527eaa5:0x793d3e9a54020aea!8m2!3d18.4620398!4d83.6622632!16s%2Fg%2F11f03szfzb?entry=ttu&g_ep=EgoyMDI2MDcxNS4wIKXMDSoASAFQAw%3D%3D'),
        ),
    ]
